// This file is auto-generated by Lovable. Do not modify it.

import { Browser } from "@capacitor/browser";
import { Capacitor } from "@capacitor/core";
import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

const LOVABLE_HOSTED_APP_URL = "https://sobable.lovable.app";
const NATIVE_OAUTH_REDIRECT_URL = `${LOVABLE_HOSTED_APP_URL}/auth-bridge`;
const lovableAuth = createLovableAuth({
  oauthBrokerUrl: `${LOVABLE_HOSTED_APP_URL}/~oauth/initiate`,
});

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      if (Capacitor.isNativePlatform()) {
        const params = new URLSearchParams({
          provider,
          redirect_uri: opts?.redirect_uri ?? NATIVE_OAUTH_REDIRECT_URL,
          ...opts?.extraParams,
        });
        const brokerUrl = `${LOVABLE_HOSTED_APP_URL}/~oauth/initiate?${params.toString()}`;

        console.debug("[lovable.auth] opening native oauth broker", {
          provider,
          redirectUri: opts?.redirect_uri ?? NATIVE_OAUTH_REDIRECT_URL,
          extraParams: opts?.extraParams ?? null,
          brokerUrl,
        });

        await Browser.open({
          url: brokerUrl,
          presentationStyle: "popover",
        });

        return { error: null, redirected: true as const };
      }

      console.debug("[lovable.auth] starting web oauth", {
        provider,
        redirectUri: opts?.redirect_uri ?? null,
        extraParams: opts?.extraParams ?? null,
      });

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      console.debug("[lovable.auth] web oauth result", {
        provider,
        result,
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
